version: '3.1'
services:
  devops-db:
    image: postgres:latest
    container_name: devops-db
    restart: always
    environment:
      POSTGRES_DB: devops-project
      POSTGRES_USER: devops-user
      POSTGRES_PASSWORD: devops-pass123
  devops-ci:
    image: sonarqube:latest
    container_name: devops-ci
    restart: always
  devops-main:
    container_name: devops-main
    restart: always
    environment:
      POSTGRES_DB: devops-project
      POSTGRES_USER: devops-user
      POSTGRES_PASSWORD: devops-pass123
    ports:
      - "163.172.64.25:8080:80"
    depends_on:
      - devops-db
      - devops-ci
    build: .
