"""empty message

Revision ID: 708ba9cd33b3
Revises: dbb6b3832462
Create Date: 2019-05-02 13:35:21.512387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708ba9cd33b3'
down_revision = 'dbb6b3832462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lights')
    op.add_column('rooms', sa.Column('comment', sa.String(length=128), nullable=False))
    op.add_column('rooms', sa.Column('status', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'rooms', ['comment'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_column('rooms', 'status')
    op.drop_column('rooms', 'comment')
    op.create_table('lights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('room', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['room'], ['rooms.id'], name='lights_room_fkey'),
    sa.PrimaryKeyConstraint('id', name='lights_pkey'),
    sa.UniqueConstraint('name', name='lights_name_key')
    )
    # ### end Alembic commands ###
