"""empty message

Revision ID: b3f875d3ec0e
Revises: 708ba9cd33b3
Create Date: 2019-05-03 20:12:52.014681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f875d3ec0e'
down_revision = '708ba9cd33b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('gpio', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'rooms', ['gpio'])
    op.drop_column('rooms', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_column('rooms', 'gpio')
    # ### end Alembic commands ###
